#!/usr/bin/env python3
"""Embed selected luciaos-assets SVGs into src/luce_ui/icon_assets.lucb.

Each editor IconKind maps to one asset; the SVG source is inlined (whitespace
collapsed, quotes escaped) so the editor has no runtime dependency on the assets
repo. Re-run when the icon set changes."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT.parent / "luciaos-assets" / "rounded" / "icons"

# IconKind name -> asset path (relative to rounded/icons/)
ICONS = {
    "folder": "common/files/folder.svg",
    "folder_open": "common/files/folder-open.svg",
    "file": "common/files/file.svg",
    "code": "code/editing/code.svg",
    "terminal": "code/editing/terminal.svg",
    "settings": "common/interface/settings.svg",
}

def load(rel: str) -> str:
    text = (ASSETS / rel).read_text()
    text = re.sub(r"\s+", " ", text).strip()      # collapse whitespace
    return text.replace('"', '\\"')                # escape for a Base string literal

lines = [
    "## Generated by tools/icons.py from luciaos-assets — do not edit by hand.",
    "## Rounded icons by Dy Mokomi (luciaos-assets), CC BY 4.0.",
    "",
    "## The SVG source for an editor icon name, or empty when unknown.",
    "pub func source(name: str) -> str:",
]
for name, rel in ICONS.items():
    lines.append(f'    if name == "{name}":')
    lines.append(f'        return "{load(rel)}"')
lines.append('    return ""')

out = ROOT / "src/luce_ui/icon_assets.lucb"
out.write_text("\n".join(lines) + "\n")
print("wrote", out, "with", len(ICONS), "icons")
